name: splendor_shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  uuid: ^4.2.1
  collection: ^1.18.0
  meta: ^1.10.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.0
  build_runner: ^2.4.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
