name: splendor_server
description: A WebSocket game server for Splendor.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
  uuid: ^4.0.0
  # Internal Shared Library
  splendor_shared:
    path: ../splendor_shared

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  async: ^2.11.0
